Repository esa/LADDS, pull requests merged in 2022-05, with the labels that each got.

#131 Paper results analysis
  notebooks/Input Dataset Processing.ipynb
  notebooks/Results Analysis.ipynb
Labels: Notebooks

#137 Changed default value to radius 5cm , i.e. 10cm size particles.
  src/ladds/Simulation.cpp
Labels: Bug

#135 LADDS Namespace
  src/ladds/CollisionFunctor.cpp
  src/ladds/CollisionFunctor.h
  src/ladds/Simulation.cpp
  src/ladds/Simulation.h
  src/ladds/TypeDefinitions.h
  src/ladds/io/ConfigReader.cpp
  src/ladds/io/ConfigReader.h
  src/ladds/io/ConjuctionLogger.cpp
  src/ladds/io/ConjunctionLogger.h
  src/ladds/io/ConjunctionWriterInterface.h
  src/ladds/io/DatasetReader.cpp
  src/ladds/io/DatasetReader.h
  src/ladds/io/Logger.cpp
  src/ladds/io/Logger.h
  src/ladds/io/SatelliteLoader.cpp
  src/ladds/io/SatelliteLoader.h
  src/ladds/io/Timers.cpp
  src/ladds/io/Timers.h
  src/ladds/io/VTUWriter.cpp
  src/ladds/io/VTUWriter.h
  src/ladds/io/hdf5/HDF5Definitions.h
  src/ladds/io/hdf5/HDF5Reader.cpp
  src/ladds/io/hdf5/HDF5Reader.h
  src/ladds/io/hdf5/HDF5Writer.cpp
  src/ladds/io/hdf5/HDF5Writer.h
  src/ladds/main.cpp
  src/ladds/particle/BreakupWrapper.cpp
  src/ladds/particle/BreakupWrapper.h
  src/ladds/particle/Constellation.cpp
  src/ladds/particle/Constellation.h
  src/ladds/particle/Particle.cpp
  src/ladds/particle/Particle.h
  src/ladds/particle/SatelliteToParticleConverter.h
  src/ladds/templateInstantiations/AutoPasClass.cpp
  src/ladds/templateInstantiations/iteratePairwiseCollisionFunctor.cpp
  tests/testladds/CollisionFunctorIntegrationTest.cpp
  tests/testladds/CollisionFunctorIntegrationTest.h
  tests/testladds/CollisionFunctorTest.cpp
  tests/testladds/SimulationTest.cpp
  tests/testladds/SimulationTest.h
  tests/testladds/io/hdf5/HDF5WriterReaderTest.cpp
  tests/testladds/particle/BreakupWrapperTest.cpp
  tests/testladds/particle/BreakupWrapperTest.h
  tests/testladds/particle/SatelliteToParticleConverterTest.cpp
Labels: Refactoring
